# -*- coding: utf-8 -*-
"""Lab2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

x = float(input("Enter X = "))
y = float(input("Enter Y = "))

tri = (1/2)*x*(y-0.8*y)
rec = (0.8*y)*(x/2)
total = tri+rec

print("Total area of the hsape is %.2f square units." % total)