# -*- coding: utf-8 -*-
"""Lab2_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

its = float(input("Enter grade from ITS100:"))
el = float(input("Enter grade from EL171:"))
scs = float(input("Enter grade from SCS183:"))

cal_its = its*3
cal_el = el*3
cal_scs = scs*1

cal_total = (cal_its+cal_el+cal_scs)/7

print("\nYour GPA is %.2f"%cal_total)