# -*- coding: utf-8 -*-
"""Lab2_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

weight = float(input("Enter your weight in kg. :"))
height = float(input("Enter your height in cm. :"))

cal_w = weight*2.20462262
cal_h = height*0.032808399

print("Your weight in pounds = %.2f"% cal_w)
print("Your height in feet = %.2f"% cal_h)