# -*- coding: utf-8 -*-
"""Lab2_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

E_1 = int(input("Enter the first number :"))
E_2 = int(input("Enter the second number :"))
E_3 = int(input("Enter the third number :"))
E_4 = int(input("Enter the first number :"))
E_5 = int(input("Enter the second number :"))
E_6 = int(input("Enter the third number :"))

print("print reverse order of %d %d %d %d %d %d ----> %d %d %d %d %d %d"% (E_1,E_2,E_3,E_4,E_5,E_6,E_6,E_5,E_4,E_3,E_2,E_1))