# -*- coding: utf-8 -*-
"""Lab2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

choc = int(input("Enter amount of melted chocolate to be poured into the cup (ml):"))
milk = int(input("bEnter amount of milk to be poured into the cup (ml):"))

total_ml = choc+milk
total_oz = total_ml*0.0338


print("Now Emmy's cup is filled with %.2f ml (or about %.2f oz) of chocolate milk." % (total_ml,total_oz))