# -*- coding: utf-8 -*-
"""Lab2_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

total = int(input("Enter four-digit integer : "))

first = total//100
second = total%100

sum = first+second
sub = first-second
div = first/second
rem = first%second

print("The result of %d + %d = %d" % (first,second,sum))
print("The result of %d - %d = %d" % (first,second,sub))
print("The interger value of %d/%d = %d" % (first,second,div))
print("The reminder of %d/%d = %d" % (first,second,rem))