# -*- coding: utf-8 -*-
"""Lab2_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

r = input("Input radius (cm) :")
h = input("Input height (cm) :")

rad = float(r)
hight = float(h)

total = 3.1415926535*rad**2*hight

print("The volume of cylinder is %.5f cubic centimeter" % total)