# -*- coding: utf-8 -*-
"""Lab2_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

first = float(input("Enter the 1st number :"))
second = float(input("Enter the 2nd number :"))
third = float(input("Enter the 3rd number :"))

print("a,b,c = %.2f, %.2f, %.2f" % (first,second,third))

sum = first+second+third
average = (sum)/3
mul = first*second*third

print("The average of three integers = %.2f"% average)
print("The summation of three intergers = %.2f"% sum)
print("The multiplication of three integers = %.2f"% mul)