# -*- coding: utf-8 -*-
"""Lab2_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

Score_F = float(input("Enter Full score = "))
Score_R = float(input("Enter Real score = "))

cal = (Score_R/Score_F)*100

print("----------------------------")
print("--- Calculate Percentage ---")
print("----------------------------")
print("Full score : %f"% Score_F)
print("Real score : %f"% Score_R)
print("----------------------------")
print("Percentage : %.2f%%"% cal)
print("----------------------------")