# -*- coding: utf-8 -*-
"""Lab2_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwlwLNM9tqv9hq1lCL4tAVjtVc8pzICn
"""

x = int(input("Enter the first integer number : "))
y = int(input("Enter the second interger number : "))

sum = (X+Y)
sub = (X-Y)
mul = (X*Y)
div = (X//Y)

print("The sum is %d"% sum)
print("The differnce is %d"% sub)
print("The product is %d"% mul)
print("The quotient is %d"% div)