<?php

// 1) Show errors while developing
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// 2) Give script enough time (Python + Vosk + Groq can take a bit)
ini_set('max_execution_time', 300);
set_time_limit(300);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    die("Invalid request method.");
}

// 3) Check file upload
if (!isset($_FILES['audioFile'])) {
    die("No file uploaded (audioFile not found).");
}

echo "DEBUG: upload1.php is running.<br>";

$errorCode = $_FILES['audioFile']['error'];
echo "DEBUG: audioFile error code = " . $errorCode . "<br>";

if ($errorCode !== UPLOAD_ERR_OK) {
    die("Upload error, code = " . $errorCode);
}

// 4) Save file into /uploads
$uploadDir = __DIR__ . '/uploads';
if (!is_dir($uploadDir)) {
    mkdir($uploadDir, 0777, true);
}

$tmpName   = $_FILES['audioFile']['tmp_name'];
$origName  = basename($_FILES['audioFile']['name']);
$safeName  = preg_replace('/[^A-Za-z0-9_\.-]/', '_', $origName);

$targetPath = $uploadDir . '/' . $safeName;

if (!move_uploaded_file($tmpName, $targetPath)) {
    die("Failed to move uploaded file.");
}

// 5) Run Python pipeline (auto_podcast.py) on the saved file

// Path to your venv python
$python = __DIR__ . '/venv/bin/python';

// Path to your Python script
$script = __DIR__ . '/auto_podcast.py';

// Build command: python auto_podcast.py <uploaded_file_path>
$cmd = escapeshellarg($python) . ' ' .
       escapeshellarg($script) . ' ' .
       escapeshellarg($targetPath);

// DEBUG: show command
echo "DEBUG: Running command:<br><code>" . htmlspecialchars($cmd) . "</code><br>";

// Run command and capture output
$output = [];
$returnVar = 0;
exec($cmd . ' 2>&1', $output, $returnVar);

// 6) Read summary text file generated by auto_podcast.py
$summaryFile = __DIR__ . '/voxly_summary.txt';
$summaryText = '';
if (file_exists($summaryFile)) {
    $summaryText = file_get_contents($summaryFile);
}

// 7) Render HTML result
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Audio Summary Result</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<div class="container">
    <h1>Upload & Conversion Result</h1>

    <p>Uploaded file: <strong><?php echo htmlspecialchars($safeName); ?></strong></p>

    <?php if ($returnVar !== 0): ?>
        <h2>Python Error (for debugging)</h2>
        <pre><?php echo htmlspecialchars(implode("\n", $output)); ?></pre>
    <?php else: ?>
        <p>Python script finished with code: <?php echo $returnVar; ?></p>
    <?php endif; ?>

    <?php if ($summaryText): ?>
        <h2>Summary</h2>
        <pre><?php echo htmlspecialchars($summaryText); ?></pre>
    <?php else: ?>
        <p>No summary was generated (output_summary.txt not found or empty).</p>
    <?php endif; ?>

    <p><a href="index.html">Back to upload</a></p>
</div>
</body>
</html>
